spring.config.import=optional:file:.env[.properties]
spring.application.name=ContentService

server.port=${CONTENT_SERVICE_PORT:8083}

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none